### ISSUE TITLE
Shows for adblock users

### ISSUE THREAD

**Issue by koreos** [clemdesign/grav-plugin-adsense2#1]
Hi, is it possible to create this plugin to show ads for adblock users (for example Adblock Plus)? I have only one ads on my website on the bottom on every page.

**Comment by clemdesign** [comment]
Hi,
Sorry but I'm afraid I do not understand. Do you means to develop a plugin for another Ads platform than Adsense?
According to my knowledge, Adblock is a tools to block/remove ads from navigator. This is not the purpose of this plugin (Manage Ads from Adsense on user page)
