### ISSUE TITLE
Slot Page Unique ID auto reset

### ISSUE THREAD

**Issue by zwitterio** [clemdesign/grav-plugin-adsense2#4]
Everytime I open settings section of Adsense2, in admin panel, it resets a _slot number_ for my page ads. It had taken a while for me to understand the problem, but now I can tell for sure that it is a bug into the blueprint or something.

I had solved the problem, by now, editing the yaml file and avoiding to open the plugin settings in admin panel. I hope this will be useful to help other guys in not wasting their time with this bug. 
Anyway, that's a really good plugin, so thank you.

**Comment by clemdesign** [comment]
@zwitterio what is the event lead to reset slot number? When you click on "Save" button, when you load Admin page or another?

It slot number the only field impacted?

What is your Grav version?

**Comment by zwitterio** [comment]
Last stable version: 1.58
The event is the click on "save" in the admin page of the plugin.
The slot number seems the only field impacted but I'm not too sure.

**Comment by clemdesign** [comment]
I try to reproduce your issue with the last version of Grav but I can't.
Plugin works correctly with me (No slot number reset on "Save" event).

Maybe you have another plugin or specific configuration that impact the behavior?

**Comment by zwitterio** [comment]
I'm very surprised. I thouht it was a problem of Adsense2. I'll try with other settings and I will tell you if I find the problem. Thanks again

**Comment by clemdesign** [comment]
Did you find the problem? I close this issue while waiting.

**Comment by zwitterio** [comment]
I'm sorry, I had too work in this weeks and I didn't try as I shoulded
