### ISSUE TITLE
I'm deleting my repo

### ISSUE THREAD

**Issue by muuvmuuv** [clemdesign/grav-plugin-adsense2#5]
I'm deleting my repo "https://github.com/muuvmuuv/grav-plugin-adsense" so you can have the name. Would have been cool to have you seen creating a pull request on my repo instead of coping it, that is how a community works... and GitHub.

**Comment by clemdesign** [comment]
Create a pull request on your repo led to modify the deep structure of your work, and finding a common solution could have been complicated.
I can understand that you are disappointed but it was more easy to create another version with new design (which satisfy my need) using some bundles of your work.
I consider 2 distinct plugins: yours and this one. I think that the current naming strategy can be keep. What do you think?
Best!

**Comment by muuvmuuv** [comment]
I think creating an issue and explaining your needs and what you would have expected the plugin should do would have been a better start. But it's fine, I haven't looked into the code a long time and can understand that a refactoring makes more sense and is faster in most cases but I also think that naming is important for people to avoid confusion. If I were someone new to Grav and look for a plugin that displays ads I would now have two choices where I couldn't say which is better especially because its named "2" but has a different owner. I can't tell how Grav is handling renaming in case of updates but I think its worth doing it.

I'll keep my repo active but will delete it later the month so feel free to make a "last" copy, especially of the logo without the 2.

**Comment by clemdesign** [comment]
We could have long discussions about each position. Good start would have been possibility to manage custom branch through Grav, but there was not possible. 

Because a lot of dependencies to the name/path, I think rename the repo can be complex and have some impacts. It's more simple to keep this naming.

If you want to not maintened your own and delete it, users will not be confused about choices.

Best!
