### ISSUE TITLE
Ads dont show up

### ISSUE THREAD

**Issue by starik1968** [clemdesign/grav-plugin-adsense2#6]
Hello, i activated AutoAds but nothing shows up. What can be wrong? I got my Client-iD and puttet it in.

Thanks in advance

**Comment by clemdesign** [comment]
Hi, I shall analyze and come back as soon.

**Comment by clemdesign** [comment]
So, I discovered an integration issue in the plugin. I prepare a correction and will publish a new release.

**Comment by clemdesign** [comment]
I published a new release [1.1.4](https://github.com/clemdesign/grav-plugin-adsense2/releases/tag/1.1.4) with correction.
Please try again.
Note: Auto Ads need few days after enabling on website to be able to display ads.
